### ISSUE TITLE
Destination is too short

### ISSUE THREAD

**Issue by dingdalong** [KumoKyaku/KCP#1]
https://github.com/KumoKyaku/KCP/blob/fec061b41eda7637a16032ff0de26e760f925222/KCP/Kcp.cs#L1006

这一行是否需要指定拷贝长度，修改为：
data.Slice(offset,(int)length).CopyTo(seg.data);

**Comment by KumoKyaku** [comment]
是的，这是一个BUG。今晚回家时我会修复它，并上传新的Nuget包。
