### ISSUE TITLE
能不能提供udp和kcp结合起来的例子呢

### ISSUE THREAD

**Issue by xizhengchao** [KumoKyaku/KCP#15]
请问能不能写个udp客户端和服务端的例子呢，发红包写下，不知道怎么弄了。

**Comment by KumoKyaku** [comment]
https://github.com/KumoKyaku/KCP/blob/master/KCP/SimpleKcpClient.cs
https://github.com/KumoKyaku/KCP/tree/master/TestServer
https://github.com/KumoKyaku/KCP/tree/master/TestClient

9201f90305e8cf716db90cb47fdd5fb32fd33433

**Comment by xizhengchao** [comment]
非常感谢，确实有用

**Comment by xizhengchao** [comment]
有群之类的吗

**Comment by KumoKyaku** [comment]
没有群
