### ISSUE TITLE
大佬，在多个线程里调用Update会报错：无法访问已经释放的对象

### ISSUE THREAD

**Issue by qulingbianji** [KumoKyaku/KCP#16]
麻烦查查

**Comment by KumoKyaku** [comment]
确定对象没有被释放么？有工程没有？

**Comment by KumoKyaku** [comment]
没有工程不能确定是bug还是用法错误

**Comment by qulingbianji** [comment]
throw new ObjectDisposedException(nameof(KcpInnerBuffer)); 我不知道是在哪引发的这个报错，工程没整理太乱了，只能等下班有空了。

**Comment by qulingbianji** [comment]
public class KCPHandle : IKcpCallback
{
    IPEndPoint target;
    UdpClient socket;
    public KCPHandle(IPEndPoint target,UdpClient socket) 
    {
        this.target = target;
        this.socket = socket;
    }
    public void Output(IMemoryOwner<byte> buffer, int avalidLength)
    {
        var s = buffer.Memory.Span.Slice(0, avalidLength).ToArray();
        socket.SendAsync(s, s.Length, target);
        buffer.Dispose();
    }
}

**Comment by KumoKyaku** [comment]
你这些都是没有用的信息，没发查
