### ISSUE TITLE
示例中两个客户端连接一个伺服器会发生延迟或丢包？

### ISSUE THREAD

**Issue by Feather46** [KumoKyaku/KCP#18]
![0](https://user-images.githubusercontent.com/104243142/170860107-29552222-c577-45a1-a526-91627ad6d88c.gif)
我不太懂这方面的内容>_<

**Comment by KumoKyaku** [comment]
没丢，只是鼠标选中了控制台，打印不出来日志了。

**Comment by Feather46** [comment]
抱歉前几天我在学校无法回覆消息
我还有一个很愚蠢的问题，kcp.Send函数为int的类型是怎样把消息发送出去的,？

**Comment by KumoKyaku** [comment]
没看懂你的问题

**Comment by Feather46** [comment]
![image](https://user-images.githubusercontent.com/104243142/171646144-ab048ca1-8f26-44d6-a7dc-482d448b4f71.png)
我是指这一段，不明白为什么可以将消息发送出去

**Comment by Feather46** [comment]
阿噢，我好像知道了，抱歉打扰了
