### ISSUE TITLE
没什么运行指南吗，VS打开都直接报错

### ISSUE THREAD

**Issue by yogioh123456** [KumoKyaku/KCP#19]

**Comment by yogioh123456** [comment]
![image](https://user-images.githubusercontent.com/25069988/172320933-b4a95b97-173c-41ad-8215-a2e47f83ef84.png)

**Comment by destinyzhang** [comment]
哥们这个问题 也就我好心回答你 其他人可能都觉得回答你算浪费时间 dll和exe你搞清楚了么?

**Comment by yogioh123456** [comment]
懂了
