### ISSUE TITLE
rcv_queue 创建buffer和UncheckRecv拷贝数据时有几率会造成越界

### ISSUE THREAD

**Issue by mycks** [KumoKyaku/KCP#21]
.....
   var buffer = CreateBuffer(peekSize);
  var recvlength = UncheckRecv(buffer.Memory.Span);
....
 seg.data.CopyTo(buffer.Slice(recvLength));

初步确认应该是线程安全问题

**Comment by KumoKyaku** [comment]
有可以复现的测试用例吗，没有复现这个bug

**Comment by mycks** [comment]
@KumoKyaku [KCP-master.zip](https://github.com/KumoKyaku/KCP/files/9817431/KCP-master.zip)

**Comment by mycks** [comment]
运行TestServer 再运行TestClient

**Comment by mycks** [comment]
@KumoKyaku 运行TestServer 再运行TestClient

**Comment by mycks** [comment]
刚更新到最新的版本没这个bug了，完美运行

**Comment by KumoKyaku** [comment]
测试代码不合法，不能while (true)Send 测试代码中Send里面调用了异步的TryRecv。异步挂起的时候会导致多线程同时TryRecv。支持多线程只得是支持Update Send Recv三个函数可以在多线程调用。但是不可以多线程同时Send或者Recv，这会导致竞赛条件。

**Comment by KumoKyaku** [comment]
增加说明 https://github.com/KumoKyaku/KCP#%E7%BA%BF%E7%A8%8B%E5%AE%89%E5%85%A8

**Comment by mycks** [comment]
1. 非常感谢！新开了线程后解决了我的问题
