### ISSUE TITLE
2个客户端请求一个服务器时有一个客户端不会收到消息

### ISSUE THREAD

**Issue by mycks** [KumoKyaku/KCP#24]
用的TestClient启动了2个客户端，但是有一个客户端收不到消息。下面时客户端的修改代码

using System;
using System.Buffers;
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Net.Sockets.Kcp;
using System.Net.Sockets.Kcp.Simple;
using System.Threading.Tasks;

namespace TestClient
{
    class Program
    {
        public class TestClient
        {
            public string guid;
           
            public void Init(string guid,int prot,uint uit)
            {
                this.guid = guid;
                SimpleKcpClient kcpClient = new SimpleKcpClient(prot, uit,end);
                kcpClient.kcp.TraceListener = new ConsoleTraceListener();
                Task.Run(async () =>
                {
                    while (true)
                    {
                        kcpClient.kcp.Update(DateTimeOffset.UtcNow);
                        await Task.Delay(10);
                    }
                });
                Task.Run(async () =>
                {
                    while (true)
                    {
                        // var k = Console.ReadKey();
                        // if (k.Key == ConsoleKey.A)
                        {
                            Send(kcpClient, "发送一条消息" + guid);
                        }
                        await Task.Delay(0);
                    }
                });
            }

            static IPEndPoint end = new System.Net.IPEndPoint(System.Net.IPAddress.Loopback, 40001);

             async void Send(SimpleKcpClient client, string v)
            {
                var buffer = System.Text.Encoding.UTF8.GetBytes(v);
                client.SendAsync(buffer, buffer.Length);
                var resp = await client.ReceiveAsync();
                var respstr = System.Text.Encoding.UTF8.GetString(resp);
                Console.WriteLine($"{guid}  收到服务器回复:    {respstr}");
            }
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Press F1 send word.......");

            TestClient testClient = new TestClient();
            testClient.Init("客户端1号",50001,2001);
            TestClient ttt2 = new TestClient();
            ttt2.Init("客户端2号",50002,2001);
            Console.ReadLine();
        }
    }
}

**Comment by KumoKyaku** [comment]
先启动testserver,再启动一个testclient。
为什么要启动2个client？

**Comment by mycks** [comment]
想模拟下多客户端的效果

**Comment by KumoKyaku** [comment]
这不是bug

**Comment by mycks** [comment]
是我什么地方没用对吗？望指教

**Comment by KumoKyaku** [comment]
目前没有时间。
你可以用搜索引擎学一下kcp用法。

**Comment by mycks** [comment]
好的3Q
