### ISSUE TITLE
非托管的GC表现如何?可以做到0GC吗?

### ISSUE THREAD

**Issue by InMyBload** [KumoKyaku/KCP#28]

**Comment by KumoKyaku** [comment]
发送接受数据时是0gc allocate的。
创建kcp对象什么的，内部数据结构什么的，还是要分配一点的。

**Comment by InMyBload** [comment]
> 发送接受数据时是0gc allocate的。 创建kcp对象什么的，内部数据结构什么的，还是要分配一点的。

和C版  相比 性能 差距大吗

**Comment by YYHEggEgg** [comment]
> 和C版 相比 性能 差距大吗

上层封装设计合理应该没问题吧。自己用的协议栈测试下来还是很出色的，虽然没有做过 C/C++ 的等价实现，但个人认为只要你用 C# 那么比 PInvoke + 一堆锁好使是很有把握的（锁争抢的厉害还有吃 CPU 的问题）。

**Comment by KumoKyaku** [comment]
> > 发送接受数据时是0gc allocate的。 创建kcp对象什么的，内部数据结构什么的，还是要分配一点的。
> 
> 和C版 相比 性能 差距大吗

没做过性能测试。
应该差距不大的。
