### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by HandOfSorrow** [KumoKyaku/KCP#3]
1457行 foreach (var seg in snd_buf)

存在线程安全问题，在另外线程中执行Dispose，snd_buf为产生空引用异常。

**Comment by KumoKyaku** [comment]
已确认，Dispose没有做线程安全处理。会在下个版本修复。
修复后会改为抛出 ObjectDisposedException

**Comment by charliewwdev** [comment]
支持一下 https://github.com/WangCharlie/douyin
