### ISSUE TITLE
请教作者一些问题

### ISSUE THREAD

**Issue by linchenrr** [KumoKyaku/KCP#30]
第一次使用，有几点问题想请教下：
1、长连接游戏开发，前端如果没有特殊需求，是否直接用SimpleKcpClient就可以
2、服务端用SimpleKcpClient如何区分不同客户端、Session
3、是否需要自己处理粘包
4、超大数据包，是否需要自行分割成几个小数据包发送

谢谢！

**Comment by KumoKyaku** [comment]
1. 对于商业项目simplekcpclient功能是远远不够的。
2. 要自己实现
3. 不需要
4. 通常不需要，但是单个消息最大不能大于1400*窗口大小。基本上不会超。
具体商业级别代码如何写，去看我另一个库，有写好的。

**Comment by linchenrr** [comment]
好的了解
