### ISSUE TITLE
kcp断开连接后无法恢复

### ISSUE THREAD

**Issue by Cigarliu** [KumoKyaku/KCP#34]
大佬 ，我测试后发现，如果客户端重开，或者服务端重开后，会出现无法正常交互数据的情况（传输层正常，Kcp层面无响应），通过断点发现 sn对不上，还有其他因素都会导致这个问题，有咩有一个主动重置的好的方式

**Comment by YYHEggEgg** [comment]
断开连接或者timeout了就应该重新握手吧，一开始怎么建立连接的就重来一遍。有一端重开那状态都不对了

**Comment by Cigarliu** [comment]
> 断开连接或者timeout了就应该重新握手吧，一开始怎么建立连接的就重来一遍。有一端重开那状态都不对了

有什么可以快速恢复的方法吗，比如 我容忍长时间断开这段时间丢掉的包，然他们迅速恢复交互

**Comment by YYHEggEgg** [comment]
> 有什么可以快速恢复的方法吗，比如 我容忍长时间断开这段时间丢掉的包，然他们迅速恢复交互

重新连接就是快速恢复。比如kcp作者提到下层用tcp建立连接交换conv，那么tcp再连一次就好了；不管你自己怎么握手都不会慢的很夸张。“迅速恢复交互”主要困难还是在上层（逻辑层）下功夫，session和连接两层分离倒是其次，主要还是怎么处理逻辑上的状态重新同步，这个才是“快速恢复”的主要阻碍（当然这个看具体场景，如果你判断不需要那么就不需要）

当然我自己只是动动嘴皮子没实现过。如果你说的“重开”指一端的程序终止那有点难，状态保存得下功夫；如果只是超时了那就是两层分离，网络层只暴露send/recv这样的异步接口，然后如果下层断开了那么就方法阻塞直到重连完成为止

**Comment by Cigarliu** [comment]
> > 有什么可以快速恢复的方法吗，比如 我容忍长时间断开这段时间丢掉的包，然他们迅速恢复交互
> 
> 重新连接就是快速恢复。比如kcp作者提到下层用tcp建立连接交换conv，那么tcp再连一次就好了；不管你自己怎么握手都不会慢的很夸张。“迅速恢复交互”主要困难还是在上层（逻辑层）下功夫，session和连接两层分离倒是其次，主要还是怎么处理逻辑上的状态重新同步，这个才是“快速恢复”的主要阻碍（当然这个看具体场景，如果你判断不需要那么就不需要）
> 
> 当然我自己只是动动嘴皮子没实现过。如果你说的“重开”指一端的程序终止那有点难，状态保存得下功夫；如果只是超时了那就是两层分离，网络层只暴露send/recv这样的异步接口，然后如果下层断开了那么就方法阻塞直到重连完成为止

是的 我指的是上层逻辑快速恢复，下层IO层面本身是不存在无法恢复的，我用的场景是：无人机使用卫星通信，用于传输无人机的视频流和控制链路，下层网络IO用的是UDP,经常遇到的问题是：机载卫星发射器在飞行途中无法正确对星导致 下层网络IO中断，（此时KCP层面 我一直继续喂视频流数据和遥测数据），间隔一段时候，下层网络IO恢复，但KCP层面的C/S端交互异常，必须双边重新初始化对象才能交互，我断点后 发现的一个问题就是 SN对不上 差太多 ，KCP层面会主动丢弃，但还是有其他因素在里面，所以我想了解的是kcp层面 我可以做到 在这种工况下的交互异常快速恢复吗

**Comment by KumoKyaku** [comment]
kcp层永远不可能主动丢弃数据，可以核对下这一点。
如果按照文档中的api调用，理论上sn不可能对不上。
如果真的对不上，那只能重新握手，没有其他办法，kcp内部维护的报头信息很多，想重置和纠正是不可能的

**Comment by KumoKyaku** [comment]
你什么.net版本？能上quic协议优先上quic

**Comment by Cigarliu** [comment]
> 你什么.net版本？能上quic协议优先上quic
用的.net6  没试过quic 通过对比quic和kcp的优缺点 chatgpt推荐说用Kcp在卫星通信场景下使用(带宽不缺，主要是延迟高，易丢包)

**Comment by KumoKyaku** [comment]
.net7可以用微软官方的quic. nuget有.net6的第三方实现，但是不知道稳定性怎么样。
quic协议是正规RFC9000中的标准协议，也是微软实现的代码。
kcp是草根协议，我这种小卡拉米实现的代码。不是一个级别的。
kcp只是出现的年代早而已。
chatgpt它毛都不懂。我自己用能上quic优先quic，然后tcp，然后才是kcp.

**Comment by Cigarliu** [comment]
> .net7可以用微软官方的quic. nuget有.net6的第三方实现，但是不知道稳定性怎么样。 quic协议是正规RFC9000中的标准协议，也是微软实现的代码。 kcp是草根协议，我这种小卡拉米实现的代码。不是一个级别的。 kcp只是出现的年代早而已。 chatgpt它毛都不懂。我自己用能上quic优先quic，然后tcp，然后才是kcp.

哈哈 大佬 不要妄自菲薄，我感觉kcp挺好的，kcp和IO层的剥离 很方便和和其他场景结合
