### ISSUE TITLE
频繁开辟内存的性能问题

### ISSUE THREAD

**Issue by andyhebear** [KumoKyaku/KCP#8]
如果服务器端连接1000+客户端，内存开辟耗时问题
比如这样的：   
    var seg = KcpSegment.AllocHGlobal(size);
                buffer.Slice(offset, size).CopyTo(seg.data);
                offset += size;
                seg.frg = (byte)(count - i - 1);
                snd_queue.Enqueue(seg);
建议实现 ArraySegment<byte>对内存块重复利用

**Comment by KumoKyaku** [comment]
有测试数据么，或者pr一个测试用例。

**Comment by KumoKyaku** [comment]
暂时没法解决，除非手动实现内存管理。后面可以考虑暴漏回调函数，将内存分配实现交给有用户，但意义不大……
